version: '3.4'
services:
    postgres:
        image: postgres
        user: postgres
        environment: 
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            # - pgdata:/var/lib/postgresql/data 
            - /var/lib/postgresql/data 
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root 
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - 27017:27017
        volumes:
            # - mongodata:/var/lib/mongodb/data
            - /var/lib/mongodb/data # -> Anonymous volume -> Delete image, also delete its volume
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: 
            - 5672:5672 # internal port
            - 15672:15672 # access in browser port
        volumes:
            - /var/lib/rabbitmq
volumes:
    pgdata:
    mongodata: