version: '3.4'
services:
    postgres:
        image: postgres
        user: postgres
        environment: 
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            # - pgdata:/var/lib/postgresql/data 
            - /var/lib/postgresql/data 
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root 
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - 27017:27017
        volumes:
            # - mongodata:/var/lib/mongodb/data
            - /var/lib/mongodb/data # -> Anonymous volume -> Delete image, also delete its volume
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: 
            - 5672:5672 # internal port
            - 15672:15672 # access in browser port
        volumes:
            - /var/lib/rabbitmq
    auction-svc: 
        image: phuoclx/auction-svc:latest
        build: 
            context: .
            dockerfile: src/AuctionService/Dockerfile 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultDB=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports:
            - 7001:80
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: phuoclx/search-svc:latest 
        build:
            context: .
            dockerfile: src/SearchService/Dockerfile 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq 
            - AppSettings__PageSize=5
            - ConnectionStrings__MongoDB=mongodb://root:mongopw@mongodb
            - AuctionServiceUrl=http://auction-svc
        ports: 
            - 7002:80 
        depends_on:
            - mongodb 
            - rabbitmq
    identity-svc:
        image: phuoclx/identity-svc:lastest 
        build:
            context: .
            dockerfile: src/IdentityService/Dockerfile 
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80 
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
        ports:
            - 5000:80 
        depends_on:
            - postgres
    gateway-svc:
        image: phuoclx/gateway-svc:lastest 
        build:
            context: .
            dockerfile: src/GatewayService/Dockerfile 
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80 
        ports:
            - 6002:80 
volumes:
    pgdata:
    mongodata: