version: '3.4'
services:
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            # - pgdata:/var/lib/postgresql/data 
            - /var/lib/postgresql/data 
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root 
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - 27017:27017
        volumes:
            # - mongodata:/var/lib/mongodb/data
            - /var/lib/mongodb/data # -> Anonymous volume -> Delete image, also delete its volume
# volumes:
#     pgdata:
#     mongodata: