import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "CarAuctions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar />
          <main className="container mx-auto px-5 pt-10">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
